services:
  postgres-dev:
    image: postgres:16
    container_name: postgres_db_dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: acueducto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - acueducto_network_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d acueducto_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  acueducto_network_dev:

volumes:
  postgres_data_dev:
